services:
  # for eclipselinkdatacenter module
  mongodb:
    image: mongo:8.0.0  # Use the latest MongoDB image
    networks:
      - backender_network
    container_name: mongodb  # Name of the container
    ports:
      - "${MONGODB_PORT}:27017"  # Expose MongoDB on port 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}  # Set the root username
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD} # Set the root password
    volumes:
      - ./mongodbmodule/db:/data/db  # Persist data in a named volume

# for prometheusmetrics module
  prometheus:
    image: prom/prometheus:latest
    networks:
      - backender_network
    container_name: prometheus
    ports:
      - "${PROMETHEUS_PORT}:9090"  # Expose Prometheus on port 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount the Prometheus config file
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'  # Specify the config file

  grafana:
    image: grafana/grafana:latest
    networks:
      - backender_network
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password (optional)

networks:
  backender_network:
    driver: bridge
  monitoring:  # Define a custom network
