# prometheus.yml
global:
  scrape_interval: 15s  # Default scrape interval

scrape_configs:
  - job_name: 'my_application'  # Name of the job
    static_configs:
      - targets: ['localhost:7070']  # Adjust this to your application's address
