package org.interactor.modules.router.dtos;

public enum RequestType {
    GET,POST, PUT, PATCH, HEAD, TRACE, CONNECT, OPTIONS, BEFORE, BEFORE_MATCHED, AFTER_MATCHED, WEBSOCKET_BEFORE_UPGRADE, WEBSOCKET_AFTER_UPGRADE, AFTER, INVALID, DELETE
}
